language: python
matrix:
  include:
  - env: TARGET=py3
  allow_failures:
  - env: TARGET=mypy
sudo: required
services:
- docker
install:
- true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: XAGnQDpkdmnAa/vydZxGKVZ4oCQRUYgtruyntfV4O8jB3nE575gaz0S1V0FH0js0P17Tq183rtDGxWcmv5ZZmPDsZP2Hw9pY++ueShereNyzKRiVZpYpRKr9/oFu+I+Od6euhSELgLc+XJhQILbH2fs3CEOVII/DkKpbdaFeh/cVmcqB/TBb9gvjwKvWuaUE+Ans6oCgIXJ/7RUJDSpW8miTJ8QGE01WHINpuVut1c+e1XOgAQ+R9NwfWENbnyZXWe7EI9rGg54HYl8LtKD91whw2fO4oD4L81lSBLUeil1CjB58OLSuNYx5fOZQlNyQdpIG4Kac3hrBP41OgijkbjUBmP5415mAFW1EmQ+y5r4Je7hnA1iU+dD79srkVrWPJoetdmcS7GM6d6s73D/gNOM7GXadRZQoKZwe4Ap1XVWLO3ecFehWVLuYvLd9JFNPSbO4q+jsel3pANC0yAuET5GqQkRLnenehZXy4RuftuFQjjQA+kerksDirG4gtOXlKLxRgNxoRpA6yxnEWnz8uGniCSZLARS8uozGX9/LiFyepZ4TN37BACLfGRx/G/UWHdrnk6JZdKAJODGZbsb5WFd0LMH1iEUyBCbN195UhKYX4o8H/OOzQeLFcWLFwV0h2p/5y1Q5LewGlq63JHh5GLBabm0rlEo1TUn5L5FwiGw=
  on:
    tags: true
    repo: paoloserra/crystalball
