language: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=pep8
  - env: TARGET=mypy
sudo: required
services:
- docker
install:
- true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: A7WUW6quu3Cp7Oz1HehY0HaRi1wU/D3mnYwPfOHNw1hpmMR0S0re9FOUnFKBxYviF1Y3BTHZqv3mctcEl3v4aGpoEZZ6hG2gZuieIQNHwrgXF8jpMNQ7gnD0cWUB6eHvJb4lR1yrRgMdtEmmq6S6C2dw75f84xGqv7G9EmlccSh6G7xxU/zicBv//3VD6bRMNEpM4/6PPVwo0xoW3UUnyoZ5hTisdQ3tatdUifiCanumMedZNVyErmT37XP8SXSjDN1kU7H8KYciGyRau6p3s8jPqqQPbzhybezs209SLjl9dNJYV183tM1dVjDYHCl0pQ3PPs3cYzjLWUW4AmuLUluPufOKHLdv49g0/u/hJHebILopomxg94P+6DNB4byeKPgl4LeCzbdJA94KL9Z2oidyYEJBdLZE8qI9yd/Adh3Mnp1V5QQHcoSc+hY/OLomKSfZUpzaPnH9mS5MPXn4Lj23M0JXAZ5+qgvcrNEIeweYWMYrSlxH2UlSmMsJRtHeKlgms72tFB7YRoiwhR2h14oqStCmkpEdUtXmr9fOKVLTN8EWXe3gh4H7AaTD6g6ARdJRbNN6NI9Y0mbgqoRW0Zw1idfAZ8tprLlHtpExbo5z7H7uX8NIN2zp0Tg5Cx9/CjJc8z/jz/3ysl/3zkbnZqBnXbUa3MLMzlPCpLO6jAo= 
  on:
    tags: true
    repo: paoloserra/crystalball
